site:
  name: 'The Duane Storey'
  url: 'https://duanestorey.com'
  description: 'The home of engineer and world traveller, Duane Storey'
  home_description: 'Duane Storey is a an entrepreneur who has develped software used by over 40 million people'
  theme: "lumen-child"
  lang: "en"
  charset: "utf-8"
  home: "posts"
content:
  pages:
    index: false
    include_date: false
    base: /
    singular: "page"
  posts:
    index: true
    include_date: true
    base: /posts
    singular: "post"
    taxonomy:
      category:
        - "categories"
        - "category"
      tag:
        - "tags"
        - "tag"
dirs:
  core_themes: "core/themes"
options:
  debug: true
  content_per_page: 20
  reading_wpm: 238
  markdown:
    auto: true
    open_command: "open %s"
  browser:
    auto: false
    open_command: "open %s"
  beautify_html: false
  images:
    convert_to_webp: false
    generate_responsive: true
  build:
    default:
      beautify_html: false
    production:
      beautify_html: true

