site:
  name: 'The Duane Storey'
  url: 'https://duanestorey.com'
  title: 'The home of engineer and world traveller, Duane Storey'
  description: 'The Duane Storey - the personal website and blog of engineer and world traveler, Duane Storey'
  theme: lumen
  lang: en
  charset: 'utf-8'
  home: posts
content:
  pages:
    index: false
    base: /
    singular: page
  posts:
    index: true
    base: /posts
    singular: post
dirs:
  themes: "core/themes"
options:
  content_per_page: 20
images:
  convert_to_webp: false
  generate_responsive: true

